### PR TITLE
Update table docs add column alignment information

### PR DESCRIPTION
**Pull request by eugenevdm**
Usage information on how to use Laravel's `$loop` variable to align columns after publishing assets.

### CODE REVIEW

**Comment by Gustavinho** [comment]
This is a good idea actually, but instead of changing the table to align the column at X index, what if we create a sort of special field like `UI::currency()` that can modify the `td` attributes dynamically? what do you think? 

I'm afraid that if we do that, changing the alignment at X index, all of our tables would be aligned at the same column, no matter if those are not currency columns

**Comment by eugenevdm** [comment]
I'm happy to give this idea a lot more thought. For now it's super easy to change alignment per application if the assets are published so this contribution to the documentation is probably not so important.

My initial objective was to just align columns, e.g. ability to have left, middle, and right, but then I saw methods only exist in the table header, not in the table row column body, so I got stuck.

For now, maybe just close this pull request? Currency is quite another matter altogether, I'll have to think about this quite a bit too and maybe do a bit of a dive in other software to see how it's done.

**Comment by Gustavinho** [comment]
Well, you gave me an idea to create a `Cell` class, similar to the `Header` class to modify the behavior (styles in this case) of the cells, what if we close this PR and add this feature to the roadmap for next releases? what do you think?

**Comment by eugenevdm** [comment]
I think a `Cell` class is precisely what is needed! The `Header` class is already very powerful so if column data can be abstracted in a `Cell` class it would be perfect. Definitely needs to be on the roadmap! Love the idea :+1:

**Comment by Gustavinho** [comment]
Thanks to you, I hadn't thought about this before

**Pull request closed without merging**
